FROM python:3-slim-bullseye

LABEL app="adress"

WORKDIR /app

ADD . .

RUN apt update \
		&& apt upgrade -y \
    && apt -yy install --no-install-recommends gcc libmariadb-dev \
    && pip3 install -r requirements.txt \
    && apt -y remove --purge --auto-remove gcc \
    && apt -y autoremove \
    && apt -y autoclean \
    && apt -y clean \
    && rm -rf /tmp/* \
    && rm -rf /var/lib/apt/lists/* \
    && rm -rf /var/cache/apt/archives/* \
    && pip cache purge \
    && rm -rf /root/.cache/*

CMD ["uvicorn", "jacobson.api.app:app", "--host=0.0.0.0","--port=8000","--reload"]
