FROM docker.io/library/python:3-alpine

LABEL app="adress"

WORKDIR /jacobson

VOLUME .:/jacobson

EXPOSE 8000

ADD requirements.txt .

RUN apk update \
    && apk upgrade \
    && apk add --no-cache gcc musl-dev \
    && pip install --upgrade pip \
    && pip install -r requirements.txt \
    && pip cache purge

CMD ["uvicorn", "api.app:app", "--host=0.0.0.0", "--port=8000", "--reload"]
