repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
      - id: check-byte-order-marker
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-vcs-permalinks
      - id: debug-statements
      - id: check-yaml
        files: .*\.(yaml|yml)$
      - id: check-added-large-files
        args: ["--maxkb=1000"]
      - id: check-toml
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.5
    hooks:
      - id: insert-license
        name: Add license for all python files
        files: \.py$|\.pyi$
        args:
          [
            --comment-style,
            '"""||"""',
            --license-filepath,
            license-templates/LICENSE.txt,
            --fuzzy-match-generates-todo,
            --use-current-year,
            --no-space,
          ]
      - id: insert-license
        name: Add license for all Markdown files
        files: \.md$
        args:
          [
            --comment-style,
            "<!--||-->",
            --license-filepath,
            license-templates/LICENSE.txt,
            --fuzzy-match-generates-todo,
            --no-space,
          ]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff-format
        name: Ruff Formater
        exclude: |
          (?x)(
              ^build/|
              ^containers/
          )
      - id: ruff
        name: Ruff Linter
        args: [--fix, --unsafe-fixes, --exit-non-zero-on-fix]
        exclude: |
          (?x)^(
              ^build/|
              ^containers/|
              ^tests/
          )
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.2
    hooks:
      - id: mypy
        name: Mypy (Static type checker)
        exclude: |
          (?x)(
              ^build/|
              ^containers/|
              ^tests/
          )
        additional_dependencies:
          [
            "strawberry-graphql[fastapi]",
            pydantic,
            pydantic-settings,
            sqlmodel,
            pyjwt,
            "pwdlib[argon2]",
          ]
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: "0.4.18"
    hooks:
      - id: uv-lock
        name: Upgrade uv lock file
        args: ["--upgrade"]
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.29.1
    hooks:
      - id: commitizen
      - id: commitizen-branch
        stages:
          - post-commit
          - pre-push
