repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.4.0
      hooks:
          - id: end-of-file-fixer
          - id: trailing-whitespace
          - id: mixed-line-ending
          - id: check-byte-order-marker
          - id: check-executables-have-shebangs
          - id: check-merge-conflict
          - id: check-symlinks
          - id: check-vcs-permalinks
          - id: debug-statements
          - id: check-yaml
            files: .*\.(yaml|yml)$
          - id: check-added-large-files
          - id: check-toml
    - repo: https://github.com/Lucas-C/pre-commit-hooks
      rev: v1.5.1
      hooks:
          - id: insert-license
            name: Add license for all python files
            files: \.py$|\.pyi$
            args:
                [
                    --comment-style,
                    '"""||"""',
                    --license-filepath,
                    license-templates/LICENSE.txt,
                    --fuzzy-match-generates-todo,
                ]
          - id: insert-license
            name: Add license for all edgedb files
            files: \.esdl$|\.edgeql$
            args:
                [
                    --comment-style,
                    "|#|",
                    --license-filepath,
                    license-templates/LICENSE.txt,
                    --fuzzy-match-generates-todo,
                ]
          - id: insert-license
            name: Add license for all Markdown files
            files: \.md$
            args:
                [
                    --comment-style,
                    "<!--||-->",
                    --license-filepath,
                    license-templates/LICENSE.txt,
                    --fuzzy-match-generates-todo,
                ]
    - repo: https://github.com/psf/black
      rev: 23.3.0
      hooks:
          - id: black
            name: Run black (Python formatter)
            args: [--config=./pyproject.toml]
    - repo: https://github.com/asottile/blacken-docs
      rev: 1.14.0
      hooks:
          - id: blacken-docs
            name: Run black on Python code blocks in documentation files
            args: [--line-length=79, --target-version=py311]
            alias: black
            additional_dependencies: [black]
    - repo: https://github.com/astral-sh/ruff-pre-commit
      rev: v0.0.277
      hooks:
          - id: ruff
            name: Run Ruff (Python linter)
            args: [--fix, --exit-non-zero-on-fix]
    - repo: https://github.com/pre-commit/mirrors-mypy
      rev: v1.4.1
      hooks:
          - id: mypy
            name: Run Mypy (Static type checker)
            args: [--show-error-codes]
    - repo: https://github.com/python-poetry/poetry
      rev: "1.5.0"
      hooks:
          - id: poetry-check
          - id: poetry-lock
          - id: poetry-export
            args: ["-f", "requirements.txt", "-o", "requirements.txt"]
    - repo: https://github.com/compilerla/conventional-pre-commit
      rev: v2.3.0
      hooks:
          - id: conventional-pre-commit
            name: "Check Conventional Commits"
            stages: [commit-msg]
