services:
  db:
    image: docker.io/library/postgres:17-alpine
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "${DATABASE_PORT:-5432}:5432"
    volumes:
      - ./containers/database/data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 30s
      timeout: 10s
      retries: 5
  app:
    build:
      context: .
      dockerfile: ./containers/app/Containerfile.dev
    env_file: ".env"
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - "./jacobson:/jacobson/jacobson"
      - "./documentation/site:/jacobson/documentation/site"
    restart: always
