# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-4.9.2
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2024-02-05T00:54:31Z"
  labels:
    app: jacobson-dev
  name: jacobson-dev
spec:
  containers:
  - args:
    - edgedb-server
    env:
    - name: HOME
      value: /root
    - name: HOSTNAME
      value: d4a182f5a0c5
    - name: EDGEDB_SERVER_SECURITY
      value: insecure_dev_mode
    image: docker.io/edgedb/edgedb:latest
    name: edgedb-1-podified
    ports:
    - containerPort: 5656
      hostPort: 5656
    - containerPort: 8000
      hostPort: 8000
    volumeMounts:
    - mountPath: /var/lib/edgedb/data
      name: home-krisque-.local-share-containers-storage-volumes-4dd63a758be176d81176a627691f4a18da7a0cae02a5cded2d25a202c9b713b6-_data-host-0
    - mountPath: /dbschema
      name: jacobson-dbschema-host-1
  - env:
    - name: HOME
      value: /root
    - name: HOSTNAME
      value: 2122150f8bf2
    image: localhost/jacobson_app:latest
    name: app-1-podified
  volumes:
  - hostPath:
      path: /home/krisque/.local/share/containers/storage/volumes/4dd63a758be176d81176a627691f4a18da7a0cae02a5cded2d25a202c9b713b6/_data
      type: Directory
    name: home-krisque-.local-share-containers-storage-volumes-4dd63a758be176d81176a627691f4a18da7a0cae02a5cded2d25a202c9b713b6-_data-host-0
  - hostPath:
      path: /home/krisque/Personal_Projects/jacobson/dbschema
      type: Directory
    name: jacobson-dbschema-host-1
