site_name: Jacobson
repo_url: https://codeberg.org/Krisque/jacobson
repo_name: Krisque/jacobson

docs_dir: documentation/docs
site_dir: documentation/site

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tabs
    - search.suggest
    - search.highlight
    - search.share
  palette:
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Modo claro
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Modo noturno

nav:
  - Home:
    - readme: "README.md"
    - changelog: "changelog.md"
  - Api:
    - address:
      - inputs: "api/address/inputs.md"
      - types: "api/address/types.md"
    - jwt:
      - jwt_manager: "api/jwt/jwt_manager.md"
      - jwt_type: "api/jwt/jwt_type.md"
    - user:
      - inputs: "api/user/inputs.md"
      - types: "api/user/types.md"
    - app: "api/app.md"
    - auth: "api/auth.md"
    - context: "api/context.md"
    - resolvers: "api/resolvers.md"
    - schema: "api/schema.md"
    - security: "api/security.md"
  - Database:
    - migrations: "database/migrations.md"
    - models:
      - brazil: "database/models/brazil.md"
      - user: "database/models/user.md"
    - repositories:
      - brazil: "database/repositories/brazil.md"
      - pagination: "database/repositories/pagination.md"
      - user: "database/repositories/user.md"
    - engine: "database/engine.md"
  - Containers: "containers.md"
  - Plugins:
    - cep_aberto:
      - cep_aberto: "plugins/cep_aberto/cep_aberto.md"
    - viacep:
      - viacep: "plugins/viacep/viacep.md"
    - plugins_controller: "plugins/plugins_controller.md"
    - protocol: "plugins/protocol.md"
  - Tests: "tests.md"
  - Utils:
    - settings: "utils/settings.md"
  - About:
    - LICENSE: "license.md"

plugins:
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            docstring_style: google
            show_root_heading: true
  - search
  - site-urls

markdown_extensions:
  - pymdownx.tasklist
  - pymdownx.snippets
  - admonition
