FROM docker.io/library/python:3.12-alpine

WORKDIR /jacobson

VOLUME ./jacobson:/jacobson/jacobson
VOLUME ./documentation/site:/jacobson/documentation/site

EXPOSE 8000

ADD pyproject.toml /jacobson
ADD alembic.ini /jacobson

RUN apk update \
	&& apk upgrade \
	&& pip install --upgrade pip \
	&& pip install .[docs] \
	&& pip cache purge

ENTRYPOINT ["sh", "-c", "alembic upgrade head && uvicorn jacobson.api.app:app --host=0.0.0.0 --port=8000 --reload"]
