FROM ghcr.io/astral-sh/uv:python3.12-alpine AS builder

ENV UV_COMPILE_BYTECODE=1 UV_LINK_MODE=copy

WORKDIR /jacobson

RUN --mount=type=cache,target=/root/.cache/uv \
    --mount=type=bind,source=uv.lock,target=uv.lock \
    --mount=type=bind,source=pyproject.toml,target=pyproject.toml \
    uv sync --frozen --no-install-project --no-editable --no-dev

COPY pyproject.toml /jacobson
COPY uv.lock /jacobson

RUN --mount=type=cache,target=/root/.cache/uv \
    uv sync --frozen --no-editable --no-dev --extra docs

# Final Image
FROM docker.io/library/python:3.12-alpine

WORKDIR /jacobson

COPY --from=builder /jacobson/.venv /jacobson/.venv

VOLUME ./jacobson:/jacobson/jacobson
VOLUME ./documentation/site:/jacobson/documentation/site

EXPOSE 8000

ENV PATH="/jacobson/.venv/bin:$PATH"

COPY alembic.ini /jacobson

ENTRYPOINT ["sh", "-c", "alembic upgrade head && uvicorn jacobson.api.app:app --host=0.0.0.0 --reload"]
