#!/usr/bin/env python3

from sys import argv, exit
from re import search, M, U

conventional_commit_regex = (
    r"\A(?:"
    r"^(?P<type>feat|fix|ci|chore|docs|test|style|refactor|build|perf|revert)"
    r"(?:\((?P<scope>[\w-]+)\))?(?P<breaking>!)?:"
    r"\s(?P<subject>\b[\w# \t-]{3,}\b)$)(?:(?:(?P<BLANK_LINE>\n^$\n)"
    r"(?P<body>(?:^.{3,}$\n?\b){1,3}))?(?P<BLANK_LINE2>\n^$\n)"
    r"(?:(?P<breaking_change>^BREAKING\sCHANGE:\s[\s\w]+$)\n)?"
    r"(?:(?P<footer>^\w+:\s\w+)))?\n?\Z"
)

commit_message = open(argv[1]).read()

if not search('MERGE_MSG', argv[1]):
    if search(conventional_commit_regex, commit_message, M | U):
        print("Commit message is validated")
        exit(0)

    print(
        "The commit message doesn't match Conventional Commits. "
        "Help: https://www.conventionalcommits.org/en/v1.0.0/"
    )
    exit(1)
